apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shadowsocks-kcp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shadowsocks-kcp
    spec:
      containers:
      - name: shadowsocks-kcp
        image: mritd/shadowsocks:latest
        env:
        - name: SS_MODULE
          value: ss-server
        - name: SS_CONFIG
          value: -s 0.0.0.0
                 -p {{ .Values.shadowsocks.port }}
                 -m {{ .Values.shadowsocks.encrypt }}
                 -k {{ .Values.shadowsocks.password }}
                 --fast-open
        - name: KCP_FLAG
          value: "true"
        - name: KCP_MODULE
          value: kcpserver
        - name: KCP_CONFIG
          value: -t 127.0.0.1:{{ .Values.kcp.port }}
                 -l :{{ .Values.shadowsocks.port }}
                 -mode {{ .Values.kcp.mode }}
        - name: RNGD_FLAG
          value: "true"
        ports:
        - containerPort: {{ .Values.shadowsocks.port }}
        - protocol: UDP
          containerPort: {{ .Values.kcp.port }}
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
