apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shadowsocks-kcp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: shadowsocks-kcp
    spec:
      containers:
      - name: shadowsocks-kcp
        image: mritd/shadowsocks:latest
        ports:
        - containerPort: 6443
        - containerPort: 6500
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        env:
        - name: SS_MODULE
          value: ss-server
        - name: SS_CONFIG
          value: -s 127.0.0.1 -p 6500 -b 0.0.0.0 -l 1080 -m chacha20 -k test123 --fast-open
        - name: KCP_FLAG
          value: true
        - name: KCP_CONFIG
          value: -t 127.0.0.1:6443 -l :6500 -mode fast2
