kind: Service
apiVersion: v1
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: {{ .Values.shadowsocks.port }}
    targetPort: {{ .Values.shadowsocks.port }}
  - protocol: UDP
    port: {{ .Values.kcp.port }}
    targetPort: {{ .Values.kcp.port }}
  type: NodePort
