kind: Service
apiVersion: v1
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 6443
    targetPort: 6443
  - protocol: UDP
    port: 6500
    targetPort: 6500
  type: NodePort
